### ISSUE TITLE
Header/Nav With Parallax Scrolling

### ISSUE THREAD

**Issue by kellenceriani** [leiadog11/leiadog11.github.io#1]
This is more of a suggestion than anything: The Parallax scrolling is awesome, however the header/nav bar moves with the parallax scrolling and that probably isn't ideal.

Also- jack said that the resume needs to be responsive so rather than a screenshot, it would be better to do an html.

**Comment by leiadog11** [comment]
Added the navbar moving with scrolling.
Changed the resume to be a pdf on the website to help with being responsive.
