### ISSUE TITLE
Title issue when viewed on mobile devices

### ISSUE THREAD

**Issue by kforney** [leiadog11/leiadog11.github.io#2]
The title currently extends beyond its border rectangle when viewed in mobile. You could possibly reduce the font size of that element when the viewport width is below a certain size to fix this issue.

![Screenshot from 2023-02-07 18-43-55](https://user-images.githubusercontent.com/5742001/217407289-fdb442d0-e54f-4794-b259-7ed176fd7351.png)

**Comment by leiadog11** [comment]
Fixed! Thanks for finding!
